spring:

  # 静态资源处理
  resources:
    # 启动默认静态资源处理，默认启用
    add-mappings: true
    cache:
      cachecontrol:
        # 缓存响应时间，单位秒
        max-age: 3600
    chain:
      # 资源链启动缓存，默认启用
      cache: true
      # 启用资源链，默认禁用
      enabled: true
      # 启用压缩资源（gzip，brotli），默认禁用
      compressed: true
      # 启用H5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/

  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill
    username: root
    password: 333
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间（默认10分钟）
      idle-timeout: 1800000
      # 最大连接数（默认10）
      maximum-pool-size: 10
      # 自动提交（从连接池返回的连接自动提交）
      auto-commit: true
      # 最大存活时间（默认30分钟，0表示永久存活）
      max-lifetime: 1800000
      # 连接超时时间（默认30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  #Redis配置
  redis:
    host: 192.168.139.128
    port: 6379
    database: 0
    connect-timeout: 10000ms
    # 连接池
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 8
        # 最大连接阻塞等待时间
        max-wait: 10000ms
        # 最大空闲连接（默认8）
        max-idle: 200
        # 最小空闲连接，默认0
        min-idle: 5

  # RabbitMQ配置
  rabbitmq:
    # 服务器
    host: 192.168.139.128
    # 用户名
    username: guest
    # 密码
    password: guest
    # 虚拟主机
    virtual-host: /
    # 端口
    port: 5672
    listener:
      simple:
        # 消费者最少数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        # 限制消费者每次只能处理1条消息，处理完毕再继续下一条
        prefetch: 1
        # 启动时是否启动容器（默认true）
        auto-startup: true
        # 消息被拒绝时是否重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试：默认false
        enabled: true
        # 重试时间，默认1000ms
        initial-interval: 1000
        # 重试最大次数，默认为3
        max-attempts: 3
        # 重试最大间隔时间：默认10000ms
        max-interval: 10000ms
        # 重试间隔乘数，比如2.0，第一次等10s，第二次等20s，第三次等40s
        multiplier: 1

# mybatis-plus配置
mybatis-plus:
  # mapper.xml映射的位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置mybatis数据返回值别名（默认别名是类名）
  type-aliases-package: xyz.hco3o.seckill.pojo

# mybatis SQL打印（方法接口所在的包，不是mapper.xml所在的包）
logging:
  level:
    xyz.hco3o.seckill.mapper: debug